import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { entrySchema } from "./content/schema";
import { transcriptSchema } from "./content/transcriptSchema";

/**
 * entries: single feed for both projects & blog posts.
 * The "kind" field lets you separate later without moving files.
 *
 * Astro 6 requires an explicit loader and reads this config from
 * `src/content.config.ts` (the old `src/content/config.ts` path is ignored).
 * The schema itself lives in `./content/schema.ts` so it can be unit-tested
 * without Astro's build pipeline.
 */
const entries = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/entries" }),
  schema: entrySchema,
});

/**
 * transcripts: talk transcripts, one per recorded session.
 *
 * Not a second feed of posts — each item names the `entries` id it belongs to,
 * and the route joins the two so a transcript inherits its entry's draft
 * status. Bodies are generated by `scripts/vtt-to-transcript.mjs`; the
 * `.corrections.json` sidecars sitting alongside are ignored by this glob.
 */
const transcripts = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/transcripts" }),
  schema: transcriptSchema,
});

export const collections = { entries, transcripts };
